const createImages = (propertyNumber) => [
  {
    url: `https://picsum.photos/seed/property-${propertyNumber}-home-exterior/1200/800`,
    publicId: `mock-property-${propertyNumber}-photo-1`,
  },
  {
    url: `https://picsum.photos/seed/property-${propertyNumber}-bedroom/1200/800`,
    publicId: `mock-property-${propertyNumber}-photo-2`,
  },
  {
    url: `https://picsum.photos/seed/property-${propertyNumber}-living-room/1200/800`,
    publicId: `mock-property-${propertyNumber}-photo-3`,
  },
  {
    url: `https://picsum.photos/seed/property-${propertyNumber}-kitchen/1200/800`,
    publicId: `mock-property-${propertyNumber}-photo-4`,
  },
];

const properties = [
  {
    title: "Mock Seafront Villa",
    ownerName: "Ahmed Al Khalifa",
    ownerEmail: "ahmed.alkhalifa@propertyseeker.test",
    description:
      "A spacious seafront villa with bright living areas, a private garden, and views across the water.",
    listingType: "sale",
    price: 245000,
    location: "manama",
    area: 320,
    bedrooms: 4,
    bathrooms: 4,
    images: createImages(1),
  },
  {
    title: "Mock Muharraq Townhouse",
    ownerName: "Ahmed Al Khalifa",
    ownerEmail: "ahmed.alkhalifa@propertyseeker.test",
    description:
      "A modern townhouse close to local shops and cafes, with flexible space for family living.",
    listingType: "rent",
    price: 950,
    location: "muharraq",
    area: 210,
    bedrooms: 3,
    bathrooms: 3,
    images: createImages(2),
  },
  {
    title: "Mock Riffa Garden Home",
    ownerName: "Ahmed Al Khalifa",
    ownerEmail: "ahmed.alkhalifa@propertyseeker.test",
    description:
      "A calm family home in a quiet neighborhood with generous bedrooms and a landscaped garden.",
    listingType: "sale",
    price: 178000,
    location: "rifaa",
    area: 260,
    bedrooms: 4,
    bathrooms: 3,
    images: createImages(3),
  },
];

const extraProperties = [
  [
    "Fatima Al Doseri",
    "fatima.aldoseri@propertyseeker.test",
    "Mock Saar Courtyard Villa",
    "A welcoming villa with a shaded courtyard, modern kitchen, and quiet family spaces.",
    "sale",
    198000,
    "jidd hafs",
    285,
    4,
    4,
  ],
  [
    "Fatima Al Doseri",
    "fatima.aldoseri@propertyseeker.test",
    "Mock Saar Family Townhouse",
    "A bright townhouse with an open plan living room and easy access to neighborhood amenities.",
    "rent",
    850,
    "jidd hafs",
    190,
    3,
    3,
  ],
  [
    "Fatima Al Doseri",
    "fatima.aldoseri@propertyseeker.test",
    "Mock Saar Modern Home",
    "A newly finished home with clean lines, generous storage, and a private outdoor terrace.",
    "sale",
    164000,
    "jidd hafs",
    220,
    3,
    3,
  ],
  [
    "Ali Al Zayani",
    "ali.alzayani@propertyseeker.test",
    "Mock Hamad Town Residence",
    "A comfortable residence with a practical layout, private parking, and a leafy front garden.",
    "sale",
    132000,
    "hamad town",
    240,
    4,
    3,
  ],
  [
    "Ali Al Zayani",
    "ali.alzayani@propertyseeker.test",
    "Mock Hamad Town Apartment",
    "A well-kept apartment with a sunny balcony and convenient access to schools and services.",
    "rent",
    620,
    "hamad town",
    125,
    2,
    2,
  ],
  [
    "Ali Al Zayani",
    "ali.alzayani@propertyseeker.test",
    "Mock Hamad Town Villa",
    "A spacious villa offering flexible family accommodation and a generous entertaining area.",
    "rent",
    1100,
    "hamad town",
    300,
    5,
    4,
  ],
  [
    "Noor Al Khalifa",
    "noor.alkhalifa@propertyseeker.test",
    "Mock Isa Town Retreat",
    "A peaceful retreat with warm interiors, a covered patio, and room for a growing family.",
    "sale",
    156000,
    "isa town",
    230,
    4,
    3,
  ],
  [
    "Noor Al Khalifa",
    "noor.alkhalifa@propertyseeker.test",
    "Mock Isa Town Garden Flat",
    "A ground-floor flat with garden access, generous natural light, and a practical floor plan.",
    "rent",
    700,
    "isa town",
    145,
    2,
    2,
  ],
  [
    "Noor Al Khalifa",
    "noor.alkhalifa@propertyseeker.test",
    "Mock Isa Town Corner Villa",
    "A corner villa with multiple living areas, a private driveway, and excellent outdoor space.",
    "sale",
    189000,
    "isa town",
    275,
    4,
    4,
  ],
  [
    "Hassan Al Bahrani",
    "hassan.albahrani@propertyseeker.test",
    "Mock Sitra Waterfront Home",
    "A relaxed waterfront home with open views, airy bedrooms, and a bright family kitchen.",
    "sale",
    172000,
    "sitra",
    250,
    4,
    3,
  ],
  [
    "Hassan Al Bahrani",
    "hassan.albahrani@propertyseeker.test",
    "Mock Sitra Marina Apartment",
    "A modern apartment near the marina with a balcony, secure parking, and shared amenities.",
    "rent",
    780,
    "sitra",
    135,
    2,
    2,
  ],
  [
    "Hassan Al Bahrani",
    "hassan.albahrani@propertyseeker.test",
    "Mock Sitra Seaside Villa",
    "A generous seaside villa with private outdoor space and flexible rooms for entertaining.",
    "rent",
    1250,
    "sitra",
    310,
    5,
    4,
  ],
];

for (const [index, data] of extraProperties.entries()) {
  const [
    ownerName,
    ownerEmail,
    title,
    description,
    listingType,
    price,
    location,
    area,
    bedrooms,
    bathrooms,
  ] = data;
  const propertyNumber = index + 4;
  properties.push({
    title,
    ownerName,
    ownerEmail,
    description,
    listingType,
    price,
    location,
    area,
    bedrooms,
    bathrooms,
    images: createImages(propertyNumber),
  });
}

module.exports = properties;
